version: '3.2'

services:

  app:
    container_name: tpl_app
    restart: unless-stopped
    volumes:
      - ./private:/data/private:rw
      - ./web/sites/default/files:/var/www/html/web/sites/default/files

  db:
    container_name: tpl_db
    restart: unless-stopped

# volumes:
#   sites_default_files:
