name: Build Docker image and push to DockerHub

on:
  push:
    branches:
      - test
    tags:
      - '*'

env:
  IMAGE_NAME: cristiroma/template-drupal-docker

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push image
        run: |
          VERSION="${{ github.ref }}"
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
